name: CI
on: [push]
jobs:
  zig-build:
    runs-on: ubuntu-latest
    steps:
      - run: curl -o /tmp/zig.tar.xz $(curl https://ziglang.org/download/index.json 2>/dev/null | jq -r '.master | .["x86_64-linux"] | .tarball') 
      - run: tar xf /tmp/zig.tar.xz -C /tmp --strip-components=1
      - run: sudo mv /tmp/zig /usr/bin/zig
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: pwd
      - run: ls -l /usr/bin/zig
      - run: zig build
